name: CI_Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        sudo apt-get install libboost-program-options-dev libboost-filesystem-dev libboost-regex-dev libboost-system-dev
        mkdir build 
        cd build
        cmake ..
        make
        
    - name: Test-HGS
      run: |
        cd build
        ./pdphgs --instance=../instances/RBO00/Class1/U159C.PDT --it=1000 > ../Test/ci_hgs_U159C.out
        cd ../Test
        python3 compare_results.py --current=ci_hgs_U159C.out --expected=ci_hgs_U159C.exp
    
    - name: Test-RR
      run: |
        cd build
        ./pdprr --instance=../instances/RBO00/Class1/U159C.PDT --fast > ../Test/ci_rr_U159C.out
        cd ../Test
        python3 compare_results.py --current=ci_rr_U159C.out --expected=ci_rr_U159C.exp
